
activity_text = ["Écris /help pour avoir la liste des commandes",
                 "Salut mec",
                 "Tu peux écrire /random-music pour avoir des bonnes musiques",
                 "Avant j'était fais en lua (je preferais cette époque)",
                 "Ma commande /user est pas du tout copiée sur Koya",
                 "c moi WECH",
                 "Concurrent à Meriy-A",
                 "AYOON2 > MERIY-A"
                 ]

music = [    "https://youtu.be/1LBMlXqhzF0",
    "https://youtu.be/QdUszpGf3qc",
    "https://youtu.be/k_PLobF65gc",
    "https://youtu.be/luH_UfG6Dbc",
    "https://youtu.be/n2c-WFyrhdI",
    "https://youtu.be/OlVZ5sw7VAA",
    "https://youtu.be/-vln9PFIEdk",
    "https://youtu.be/yxkyElx0pXI",
    "https://youtu.be/9Zj0JOHJR-s",
    "https://youtu.be/-vjq14_c4PA",
    "https://youtu.be/gh-vFtEEd84",
    "https://youtu.be/PiMAAY3iOMk",
    "https://youtu.be/tF4faMbs5oQ",
    "https://youtu.be/UqIahGU9ZtY",
    "https://youtu.be/sfFv3MTPdkw",
    "https://youtu.be/rW7OB_HDCGQ",
    "https://youtu.be/j3qHKeZjrdU",
    "https://youtu.be/cRA5gsdCf4c",
    "https://youtu.be/7hpfhV9SLx0",
    "https://youtu.be/2OOzgf9uvF0",
    "https://youtu.be/iUfRokM267k (proposé par 88)",
    "https://youtu.be/eNOuPXINDaA (proposé par 88)",
    "https://youtu.be/sNHovxlXWQk (proposé par 88)",
    "https://youtu.be/k5Pw6FgoE6E (proposé par 88)",
    "https://youtu.be/iijKJdUDR3c",
    "https://youtu.be/sK10CbCNs18",
    "https://youtu.be/LUdMxyKZcWc",
    "https://youtu.be/j6lfJqr5Mfc",
    "https://youtu.be/wYZux3BMc5k",
    "https://youtu.be/OkMLYNWP-yo",
    "https://youtu.be/2NnJA-c1Tro",
    "https://youtu.be/yyTcgfleUqw",
    "https://youtu.be/4HiHQo0lqNI",
    "https://youtu.be/9Gj47G2e1Jc",
    "https://youtu.be/K5hVDpq6SFA",
]
